/**
 * Bodies: one torso per outfit, one arm layer per pose frame.
 *
 * Every character is 16 wide and 26 tall. The head owns rows 0-13, with two
 * spare rows on top for horns and spiky hair; the body owns rows 14-25. Arms
 * are their own layer so a pose changes only what moves, and so every outfit
 * works in every pose without being drawn again.
 *
 * Slots:
 *   o outline     c/C outfit and its shade     t trim (collar, belt, hems)
 *   u undershirt  k/K accent (tie, sash)       g gold (buttons, braid)
 *   s/S skin      n hands (skin, or gloves)    p/P legs or skirt, and shade
 *   f shoes       j/J legwear under a skirt   U paper (a held scroll)
 */

import { grid, type Grid } from '../canvas';

export const SPRITE_W = 16;
export const SPRITE_H = 26;
export const BODY_Y = 14;

export type Outfit =
    | 'tunic'
    | 'kimono'
    | 'miko'
    | 'suit'
    | 'suit-skirt'
    | 'tailcoat'
    | 'dress'
    | 'uniform'
    | 'apron'
    | 'coat'
    | 'ninja'
    | 'armor'
    | 'robe';

export const TORSOS: Record<Outfit, Grid> = {
    tunic: grid(`
        ...oooooooooo...
        ...occtsstcco...
        ...ocCcttcCco...
        ...occcccccco...
        ...oCccccccCo...
        ...otttttttto...
        ....oppppppo....
        ....oppooppo....
        ....oppooppo....
        ....oPPooPPo....
        ....offooffo....
        ....ooo..ooo....
    `),
    // Crossed collar, a wide sash, and hakama.
    kimono: grid(`
        ...oooooooooo...
        ...octssstcco...
        ...occtsstcCo...
        ...oCcctcccco...
        ...okkkkkkkko...
        ...oKkkkkkkKo...
        ...oppppppppo...
        ...oppppppppo...
        ...opppPpppPo...
        ...oPPPoPPPPo...
        ....offooffo....
        ....ooo..ooo....
    `),
    // White kosode, red ribbon, wide red hakama.
    miko: grid(`
        ...oooooooooo...
        ...occtsstcco...
        ...ocCcttcCco...
        ...occckkccco...
        ...oCcckkccCo...
        ...oppppppppo...
        ..oppppppppppo..
        ..oppppPpppppo..
        ..opppPpppPppo..
        ..oPPPPoPPPPPo..
        ....offooffo....
        ....ooo..ooo....
    `),
    // Lapels over a shirt and tie.
    suit: grid(`
        ...oooooooooo...
        ...ocuuuuuuco...
        ...occuukucco...
        ...oCcckkccCo...
        ...occcckccco...
        ...oCccccccCo...
        ....oppppppo....
        ....oppooppo....
        ....oppooppo....
        ....oPPooPPo....
        ....offooffo....
        ....ooo..ooo....
    `),
    'suit-skirt': grid(`
        ...oooooooooo...
        ...ocuuuuuuco...
        ...occuukucco...
        ...oCcckkccCo...
        ...occcckccco...
        ...oCccccccCo...
        ...oppppppppo...
        ...oppppppppo...
        ....ojjjjjjo....
        ....ojJooJjo....
        ....offooffo....
        ....ooo..ooo....
    `),
    // A high white collar, a red cravat, gold buttons, and tails.
    tailcoat: grid(`
        ...oooooooooo...
        ...ocuuuuuuco...
        ...occukkucco...
        ...occcuuccco...
        ...occguugcco...
        ...oCccuuccCo...
        ...occppppcco...
        ...ocppooppco...
        ...oCppooppCo...
        ....oPPooPPo....
        ....offooffo....
        ....ooo..ooo....
    `),
    // Fitted bodice, flared skirt.
    dress: grid(`
        ...oooooooooo...
        ...occtsstcco...
        ...ocCcttcCco...
        ...occckkccco...
        ...oCccccccCo...
        ...otttttttto...
        ...occcccccco...
        ..occcccccccco..
        ..ocCcccccCcco..
        ..oCCCCCCCCCCo..
        ....ojo..ojo....
        ....ofo..ofo....
    `),
    // Buttons and braid.
    uniform: grid(`
        ...oooooooooo...
        ...occkuukcco...
        ...ocCcggcCco...
        ...occcccccco...
        ...oCccggccCo...
        ...otttttttto...
        ....oppppppo....
        ....oppooppo....
        ....oppooppo....
        ....oPPooPPo....
        ....offooffo....
        ....ooo..ooo....
    `),
    // Shirt under a leather apron.
    apron: grid(`
        ...oooooooooo...
        ...occtsstcco...
        ...ockkkkkkco...
        ...ockKkkkkco...
        ...oCkkkkkkCo...
        ...otkkkkkkto...
        ....okkkkkko....
        ....okKkkkko....
        ....oppooppo....
        ....oPPooPPo....
        ....offooffo....
        ....ooo..ooo....
    `),
    // Open coat over a shirt.
    coat: grid(`
        ...oooooooooo...
        ...occuuuucco...
        ...ocguuuugco...
        ...occuuuucco...
        ...oCcuuuucCo...
        ...occttttcco...
        ...occppppcco...
        ...occpoopcco...
        ...oCcpoopcCo...
        ....oPPooPPo....
        ....offooffo....
        ....ooo..ooo....
    `),
    // Wrapped garb with a scarf high at the neck.
    ninja: grid(`
        ...oooooooooo...
        ...okkkkkkkko...
        ...oKkkkkkkKo...
        ...occcctccco...
        ...oCcctcccCo...
        ...otttttttto...
        ....oppppppo....
        ....oppooppo....
        ....opPooPpo....
        ....oPPooPPo....
        ....offooffo....
        ....ooo..ooo....
    `),
    // Leather with a strap across the chest.
    armor: grid(`
        ...oooooooooo...
        ...occtsstcco...
        ...okccccccco...
        ...ockcccccco...
        ...oCckccccCo...
        ...otttktttto...
        ....oppppppo....
        ....oppooppo....
        ....oppooppo....
        ....oPPooPPo....
        ....offooffo....
        ....ooo..ooo....
    `),
    // A floor-length robe.
    robe: grid(`
        ...oooooooooo...
        ...occtsstcco...
        ...occcttccco...
        ...occckkccco...
        ...oCcckkccCo...
        ...occcccccco...
        ...occcccccco...
        ...ocCccccCco...
        ...occcccccco...
        ...oCCCCCCCCo...
        ....offooffo....
        ....ooo..ooo....
    `),
};

/**
 * An arm layer. `y` is the sprite row its first line lands on; `over` draws it
 * after the head, for a hand at the chin or an arm raised past the face.
 */
export interface ArmLayer {
    grid: Grid;
    y: number;
    over?: boolean;
}

const DOWN: ArmLayer = {
    y: 14,
    grid: grid(`
        ................
        ..oo........oo..
        ..oc........co..
        ..oc........co..
        ..oC........Co..
        ..on........no..
        ...o........o...
    `),
};

// Typing at a crystal screen: hands meet the desk, one lifts at a time.
const TYPE_A: ArmLayer = {
    y: 14,
    grid: grid(`
        ................
        ..oo........oo..
        ..oc........co..
        ..occo....occo..
        ...ocno..onco...
        ....oo....oo....
    `),
};
const TYPE_B: ArmLayer = {
    y: 14,
    grid: grid(`
        ................
        ..oo........oo..
        ..oc........co..
        ..occno...occo..
        ...ooo...onco...
        ..........oo....
    `),
};
const TYPE_C: ArmLayer = {
    y: 14,
    grid: grid(`
        ................
        ..oo........oo..
        ..oc........co..
        ..occo...oncco..
        ...onco...ooo...
        ....oo..........
    `),
};

// Holding a scroll up for the CHO.
const RAISE_A: ArmLayer = {
    y: 4,
    over: true,
    grid: grid(`
        ...........oooo.
        ..........oUUUUo
        ..........oUuUUo
        ...........onno.
        ...........onno.
        ............oco.
        ............oco.
        ............oco.
        ............oco.
        ............oco.
        ............oco.
        ..oo........oco.
        ..oc........oo..
        ..oc............
        ..oC............
        ..on............
        ...o............
    `),
};
const RAISE_B: ArmLayer = {
    y: 5,
    over: true,
    grid: grid(`
        ...........oooo.
        ..........oUUUUo
        ..........oUuUUo
        ...........onno.
        ...........onno.
        ............oco.
        ............oco.
        ............oco.
        ............oco.
        ............oco.
        ..oo........oco.
        ..oc........oo..
        ..oc............
        ..oC............
        ..on............
        ...o............
    `),
};

// Both arms up.
const CHEER: ArmLayer = {
    y: 5,
    over: true,
    grid: grid(`
        .onno......onno.
        .onno......onno.
        .oco........oco.
        .oco........oco.
        .oco........oco.
        .oco........oco.
        .oco........oco.
        .oco........oco.
        .oco........oco.
        ..oo........oo..
    `),
};

// A hand at the chin.
const THINK: ArmLayer = {
    y: 11,
    over: true,
    grid: grid(`
        ................
        .........onno...
        .........onno...
        ..........occo..
        ..oo.......oco..
        ..oc.......oco..
        ..oc.......oco..
        ..oC........oo..
        ..on............
        ...o............
    `),
};

// Diablo's bow: a gloved hand on the heart.
const BOW: ArmLayer = {
    y: 14,
    grid: grid(`
        ................
        ..oo........oo..
        ..oc.......occo.
        ..oc....onncco..
        ..oC....oooo....
        ..on............
        ...o............
    `),
};

export type Pose = 'stand' | 'idle' | 'type' | 'raise' | 'slump' | 'cheer' | 'sleep' | 'think' | 'bow';

export interface PoseFrame {
    arms: ArmLayer;
    /** Rows the head drops by: a nod, a slump, sleep. */
    headDy: number;
    /** Rows the whole body moves by: negative is a hop. */
    bodyDy: number;
    eyes: 'open' | 'closed';
    /** Whether the character's own item is in hand. */
    holdsItem: boolean;
}

const f = (arms: ArmLayer, headDy = 0, eyes: 'open' | 'closed' = 'open', bodyDy = 0, holdsItem = false): PoseFrame => ({
    arms,
    headDy,
    bodyDy,
    eyes,
    holdsItem,
});

export const POSES: Record<Pose, readonly PoseFrame[]> = {
    stand: [f(DOWN, 0, 'open', 0, true), f(DOWN, 1, 'open', 0, true)],
    idle: [f(DOWN, 0), f(DOWN, 1)],
    type: [f(TYPE_A, 0), f(TYPE_B, 1), f(TYPE_A, 0), f(TYPE_C, 1)],
    raise: [f(RAISE_A, 0), f(RAISE_B, 0)],
    slump: [f(DOWN, 2), f(DOWN, 3)],
    // The hop lifts the body a row while the head holds: a squash, and no
    // horn goes off the top.
    cheer: [f(CHEER, 0, 'closed'), f(CHEER, 1, 'closed', -1)],
    sleep: [f(DOWN, 2, 'closed'), f(DOWN, 3, 'closed')],
    think: [f(THINK, 0), f(THINK, 1)],
    bow: [f(BOW, 0), f(BOW, 2, 'closed')],
};

/** Where the right hand is when standing, for the character's own item. */
export const HAND = { x: 12, y: 19 } as const;
