/**
 * Tempest, tile by tile: 16×16 ground, walls, furniture and ornaments, plus
 * the small things that float over heads.
 *
 * One palette for the whole town, so a lamp by the inn matches the lamp by
 * the hall. Slots:
 *   o outline   g/G grass   d/D path   w/W wood   s/S stone   r/R roof
 *   b/B banner  y/Y light   c/C crystal  k dark glass  p/P paper  m/M metal
 *   t trunk     l/L leaves  f flower   x/X smoke   h/H cushion   e/E brick and mortar
 */

import { grid, palette, type Grid, type Palette } from '../canvas';

export const TOWN: Palette = palette({
    o: '#1a1423',
    g: '#5f9c4b',
    G: '#4f8640',
    d: '#cfae7e',
    D: '#b59463',
    w: '#a8743f',
    W: '#82572b',
    s: '#8d929c',
    S: '#6c7280',
    r: '#4e6fae',
    R: '#3a5486',
    b: '#3b6ea8',
    B: '#2a4f7a',
    y: '#f6d36b',
    Y: '#fff4bf',
    c: '#7fd0f0',
    C: '#4aa7d8',
    k: '#2a2d3a',
    p: '#f2e8cf',
    P: '#d9ccab',
    m: '#c0c6d0',
    M: '#8a929f',
    t: '#6a4226',
    l: '#4f9a3c',
    L: '#3c7a2c',
    f: '#ee6f93',
    x: '#ececf2',
    X: '#bcc0cc',
    h: '#c8344a',
    H: '#9a2236',
    // Brick and its mortar.
    e: '#b06a4a',
    E: '#d9c2a8',
});

export const TILES = {
    grass: grid(`
        gggggGgggggggggg
        ggggGGggggggGggg
        gggggggggggGGggg
        gggggggggggggggg
        gGgggggggggggggg
        GGgggggggGgggggg
        gggggggggGGggggg
        gggggggggggggggg
        ggggggGggggggggg
        gggggGGgggggggGg
        ggggggggggggggGG
        gggggggggggggggg
        ggGggggggggggggg
        gGGggggggGgggggg
        ggggggggGGgggggg
        gggggggggggggggg
    `),
    grassTuft: grid(`
        gggggggggggggggg
        gggggggggggggggg
        ggggLggggggggggg
        gggLlLgggggggggg
        ggglllgggggggggg
        gggggggggggggggg
        ggggggggggggLggg
        gggggggggggLlLgg
        gggggggggggLllgg
        gggggggggggggggg
        gggggggggggggggg
        ggGggggggggggggg
        gGGgggggggggggGg
        gggggggggggggGGg
        gggggggggggggggg
        gggggggggggggggg
    `),
    path: grid(`
        DdddddddddddddDd
        dddDdddddddddddd
        ddddddddDDdddddd
        ddddddddddddddDd
        ddDDdddddddddddd
        dddddddddddddddd
        ddddddddddddDddd
        dDdddddDDddddddd
        dddddddddddddddd
        dddddDddddddDDdd
        dddddddddddddddd
        ddDddddddddddddd
        dddddddDDddddddd
        dddddddddddddddd
        DddddddddddddDdd
        dDdddddddddddddd
    `),
    floor: grid(`
        wwwwwwwWwwwwwwww
        wwwwwwwWwwwwwwww
        wWwwwwwWwwwwwWww
        WWWWWWWWWWWWWWWW
        wwwWwwwwwwwwWwww
        wwwWwwwwwwwwWwww
        wwwWwwWwwwwwWwww
        WWWWWWWWWWWWWWWW
        wwwwwwwWwwwwwwww
        wwwwwwwWwwwwwwww
        wWwwwwwWwwwwwWww
        WWWWWWWWWWWWWWWW
        wwwWwwwwwwwwWwww
        wwwWwwwwwwwwWwww
        wwwWwwWwwwwwWwww
        WWWWWWWWWWWWWWWW
    `),
    stoneFloor: grid(`
        ssssSssssssSssss
        sssSSssssssSSsss
        ssssSssssssSssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        SSsssssSSsssssss
        sSssssssSsssssss
        SSSSSSSSSSSSSSSS
        ssssSssssssSssss
        sssSSssssssSSsss
        ssssSssssssSssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        SSsssssSSsssssss
        sSssssssSsssssss
        SSSSSSSSSSSSSSSS
    `),
    roof: grid(`
        oooooooooooooooo
        RRRRRRRRRRRRRRRR
        rrrrRrrrrRrrrrRr
        rrrrRrrrrRrrrrRr
        RRRRRRRRRRRRRRRR
        rRrrrrRrrrrRrrrr
        rRrrrrRrrrrRrrrr
        RRRRRRRRRRRRRRRR
        rrrrRrrrrRrrrrRr
        rrrrRrrrrRrrrrRr
        RRRRRRRRRRRRRRRR
        rRrrrrRrrrrRrrrr
        rRrrrrRrrrrRrrrr
        RRRRRRRRRRRRRRRR
        oooooooooooooooo
        SSSSSSSSSSSSSSSS
    `),
    roofDark: grid(`
        oooooooooooooooo
        SSSSSSSSSSSSSSSS
        RRRRSRRRRSRRRRSR
        RRRRSRRRRSRRRRSR
        SSSSSSSSSSSSSSSS
        RSRRRRSRRRRSRRRR
        RSRRRRSRRRRSRRRR
        SSSSSSSSSSSSSSSS
        RRRRSRRRRSRRRRSR
        RRRRSRRRRSRRRRSR
        SSSSSSSSSSSSSSSS
        RSRRRRSRRRRSRRRR
        RSRRRRSRRRRSRRRR
        SSSSSSSSSSSSSSSS
        oooooooooooooooo
        SSSSSSSSSSSSSSSS
    `),
    wall: grid(`
        SSSSSSSSSSSSSSSS
        ssssssssSsssssss
        ssssssssSsssssss
        SSSSSSSSSSSSSSSS
        sssSsssssssssSss
        sssSsssssssssSss
        SSSSSSSSSSSSSSSS
        ssssssssSsssssss
        ssssssssSsssssss
        SSSSSSSSSSSSSSSS
        sssSsssssssssSss
        sssSsssssssssSss
        SSSSSSSSSSSSSSSS
        SSSSSSSSSSSSSSSS
        oooooooooooooooo
        oooooooooooooooo
    `),
    wallSide: grid(`
        oSSSSSSSSSSSSSSo
        ossssssssSssssso
        ossssssssSssssso
        oSSSSSSSSSSSSSSo
        osssSsssssssssSo
        osssSsssssssssSo
        oSSSSSSSSSSSSSSo
        ossssssssSssssso
        ossssssssSssssso
        oSSSSSSSSSSSSSSo
        osssSsssssssssSo
        osssSsssssssssSo
        oSSSSSSSSSSSSSSo
        ossssssssSssssso
        ossssssssSssssso
        oSSSSSSSSSSSSSSo
    `),
    // Timber frame: dark beams over pale plaster.
    wallTimber: grid(`
        tttttttttttttttt
        tppppppptppppppt
        tppppppptppppppt
        tppppppptppppppt
        tttttttttttttttt
        tpppptppppptpppt
        tpppptppppptpppt
        tpppptppppptpppt
        tttttttttttttttt
        tppppppptppppppt
        tppppppptppppppt
        tppppppptppppppt
        tttttttttttttttt
        tttttttttttttttt
        oooooooooooooooo
        oooooooooooooooo
    `),
    wallSideTimber: grid(`
        otttttttttttttto
        otppppppptpppppo
        otppppppptpppppo
        otttttttttttttto
        otpppptppppptppo
        otpppptppppptppo
        otttttttttttttto
        otppppppptpppppo
        otppppppptpppppo
        otttttttttttttto
        otpppptppppptppo
        otpppptppppptppo
        otttttttttttttto
        otppppppptpppppo
        otppppppptpppppo
        otttttttttttttto
    `),
    // Brick: warm courses with pale mortar.
    wallBrick: grid(`
        EEEEEEEEEEEEEEEE
        eeeeeeeEeeeeeeeE
        eeeeeeeEeeeeeeeE
        EEEEEEEEEEEEEEEE
        eeeEeeeeeeeEeeee
        eeeEeeeeeeeEeeee
        EEEEEEEEEEEEEEEE
        eeeeeeeEeeeeeeeE
        eeeeeeeEeeeeeeeE
        EEEEEEEEEEEEEEEE
        eeeEeeeeeeeEeeee
        eeeEeeeeeeeEeeee
        EEEEEEEEEEEEEEEE
        EEEEEEEEEEEEEEEE
        oooooooooooooooo
        oooooooooooooooo
    `),
    wallSideBrick: grid(`
        oEEEEEEEEEEEEEEo
        oeeeeeeeEeeeeeeo
        oeeeeeeeEeeeeeeo
        oEEEEEEEEEEEEEEo
        oeeeEeeeeeeeEeeo
        oeeeEeeeeeeeEeeo
        oEEEEEEEEEEEEEEo
        oeeeeeeeEeeeeeeo
        oeeeeeeeEeeeeeeo
        oEEEEEEEEEEEEEEo
        oeeeEeeeeeeeEeeo
        oeeeEeeeeeeeEeeo
        oEEEEEEEEEEEEEEo
        oeeeeeeeEeeeeeeo
        oeeeeeeeEeeeeeeo
        oEEEEEEEEEEEEEEo
    `),
    windowDark: grid(`
        SSSSSSSSSSSSSSSS
        ssssssssSsssssss
        ssooooooooooooss
        ssokkkkkokkkkoss
        ssokkkkkokkkkoss
        ssokkkkkokkkkoss
        ssooooooooooooss
        ssokkkkkokkkkoss
        ssokkkkkokkkkoss
        ssokkkkkokkkkoss
        ssooooooooooooss
        sSSSSSSSSSSSSSSs
        SSSSSSSSSSSSSSSS
        SSSSSSSSSSSSSSSS
        oooooooooooooooo
        oooooooooooooooo
    `),
    windowLit: grid(`
        SSSSSSSSSSSSSSSS
        ssssssssSsssssss
        ssooooooooooooss
        ssoyyyyyoyyyyoss
        ssoyYyyyoyyYyoss
        ssoyyyyyoyyyyoss
        ssooooooooooooss
        ssoyyyyyoyyyyoss
        ssoyyyyyoyyyyoss
        ssoyyyyyoyyyyoss
        ssooooooooooooss
        sSSSSSSSSSSSSSSs
        SSSSSSSSSSSSSSSS
        SSSSSSSSSSSSSSSS
        oooooooooooooooo
        oooooooooooooooo
    `),
    boarded: grid(`
        SSSSSSSSSSSSSSSS
        ssssssssSsssssss
        ssooooooooooooss
        ssokkkkkkkkkkoss
        ssWWWkkkkkkkkoss
        ssokkWWWkkkkkoss
        ssokkkkkWWWkkoss
        ssokkkkkkkkWWWss
        ssWWWkkkkkkkkoss
        ssokkWWWkkkkkoss
        ssoooooWWWooooss
        sSSSSSSSSSSSSSSs
        SSSSSSSSSSSSSSSS
        SSSSSSSSSSSSSSSS
        oooooooooooooooo
        oooooooooooooooo
    `),
    door: grid(`
        SSSSSSSSSSSSSSSS
        sssssooooooossss
        ssssoWWWWWWWosss
        sssoWwWWWWWwWoss
        sssoWWWWWWWWWoss
        sssoWWWWWWWWWoss
        sssoWWWWWWWWWoss
        sssoWWWWWWWWWoss
        sssoWWWWWWmWWoss
        sssoWWWWWWWWWoss
        sssoWWWWWWWWWoss
        sssoWWWWWWWWWoss
        sssoWWWWWWWWWoss
        sssoWWWWWWWWWoss
        oooWWWWWWWWWWooo
        oooooooooooooooo
    `),
    scaffold: grid(`
        t..............t
        tWWWWWWWWWWWWWWt
        t..............t
        t.....t........t
        t.....t........t
        tWWWWWWWWWWWWWWt
        t.....t........t
        t.....t...t....t
        t.....t...t....t
        tWWWWWWWWWWWWWWt
        t.........t....t
        t.........t....t
        t.........t....t
        tWWWWWWWWWWWWWWt
        t..............t
        t..............t
    `),
    deskOff: grid(`
        ................
        ................
        ....oooooooo....
        ...oCCCCCCCCo...
        ...oCkkkkkkCo...
        ...oCkkkkkkCo...
        ...oCCCCCCCCo...
        ....oooooooo....
        ......oMMo......
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        .oWo........oWo.
        .oWo........oWo.
        ................
        ................
    `),
    deskOn: grid(`
        ................
        ................
        ....oooooooo....
        ...oCCCCCCCCo...
        ...oCcYccccCo...
        ...oCccccccCo...
        ...oCCCCCCCCo...
        ....oooooooo....
        ......oMMo......
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        .oWo........oWo.
        .oWo........oWo.
        ................
        ................
    `),
    deskOn2: grid(`
        ................
        ................
        ....oooooooo....
        ...oCCCCCCCCo...
        ...oCccccccCo...
        ...oCcccYccCo...
        ...oCCCCCCCCo...
        ....oooooooo....
        ......oMMo......
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        .oWo........oWo.
        .oWo........oWo.
        ................
        ................
    `),
    nameplate: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..oooooooooooo..
        ..oppPpppPpppo..
        ..oppppppppppo..
        ..oooooooooooo..
        ......oWWo......
        ................
        ................
    `),
    lantern: grid(`
        ......oooo......
        .....oMMMMo.....
        ......oyyo......
        .....oyYYyo.....
        .....oyYYyo.....
        .....oyyyyo.....
        ......oyyo......
        ......oooo......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        ......oMMo......
        .....oMMMMo.....
        .....oooooo.....
    `),
    cushion: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....oooooooo....
        ..oohhhhhhhhoo..
        .ohhhhHhhhhhhho.
        .ohhhhhhhhhhhho.
        .oHHhhhhhhhhHHo.
        ..ooHHHHHHHHoo..
        ....oooooooo....
        ................
        ................
    `),
    scrolls1: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....ooooooooo...
        ...oppppppppPo..
        ...oPPPPPPPPPo..
        ...oooooooooo...
        ................
        ................
        ................
    `),
    scrolls2: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        .....ooooooooo..
        ....oppppppppPo.
        ....oPPPPPPPPPo.
        ....ooooooooooo.
        ...oppppppppPo..
        ...oPPPPPPPPPo..
        ...oooooooooo...
        ................
        ................
        ................
    `),
    scrolls3: grid(`
        ................
        ................
        ................
        ....ooooooooo...
        ...oppppppppPo..
        ...oPPPPPPPPPo..
        .....ooooooooo..
        ....oppppppppPo.
        ....oPPPPPPPPPo.
        ....ooooooooooo.
        ...oppppppppPo..
        ...oPPPPPPPPPo..
        ...oooooooooo...
        ................
        ................
        ................
    `),
    lamp: grid(`
        ......oooo......
        .....oyYYyo.....
        .....oyYYyo.....
        .....oyyyyo.....
        ......oooo......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        ......oMMo......
        .....oMMMMo.....
        ....oMMMMMMo....
        ....oooooooo....
    `),
    garden: grid(`
        ................
        ................
        ......f.........
        .....lfl....f...
        ......l....lfl..
        ..f.........l...
        .lfl......f.....
        ..l......lfl....
        ....f.....l.....
        ...lfl..........
        ....l....f......
        ........lfl.....
        .f.......l......
        lfl.......f.....
        .l.......lfl....
        ..........l.....
    `),
    banner: grid(`
        ......oooo......
        .....oMMMMo.....
        ......oMMo......
        ....oobbbboo....
        ....obbbbbbo....
        ....obBbbBbo....
        ....obbbbbbo....
        ....obbyybbo....
        ....obbyybbo....
        ....obbbbbbo....
        ....obBbbBbo....
        ....obbbbbbo....
        ....obb..bbo....
        ....oo....oo....
        .......MM.......
        ......oMMo......
    `),
    statue: grid(`
        ......oooo......
        .....ommmmo.....
        .....ommMmo.....
        ......ommo......
        ....oommmmoo....
        ...ommmmmmmmo...
        ...ommMmmMmmo...
        ...ommmmmmmmo...
        ....ommmmmmo....
        ....ommmmmmo....
        ....oMMMMMMo....
        ...oSSSSSSSSo...
        ..oSSSSSSSSSSo..
        ..oSsssssssSSo..
        ..oSSSSSSSSSSo..
        ..oooooooooooo..
    `),
    tree: grid(`
        ......oooo......
        ....oollllloo...
        ...ollllllllLo..
        ..olllllllllLLo.
        ..ollLlllllllLo.
        .ollllllllLllLLo
        .olLllllllllllLo
        .oLlllllLlllLLLo
        ..oLLlllllllLLo.
        ..ooLLLLLLLLLoo.
        ....oooottoooo..
        .......ott......
        .......ott......
        .......ott......
        ......oottoo....
        ......oooooo....
    `),
    chimney: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        .....oooooo.....
        .....oSSSSo.....
        .....osssso.....
        .....osSsso.....
        .....osssso.....
        .....oSsSso.....
        .....osssso.....
        .....oooooo.....
        ................
        ................
    `),
    smokeA: grid(`
        ................
        ................
        ......xx........
        .....xXxx.......
        ......xx........
        ................
        ........xx......
        .......xxXx.....
        ........xx......
        ................
        ......xxx.......
        .....xXxxx......
        ......xxx.......
        ................
        ................
        ................
    `),
    smokeB: grid(`
        ................
        ........xx......
        .......xXxx.....
        ........xx......
        ................
        .....xx.........
        ....xxXx........
        .....xx.........
        ................
        .......xxx......
        ......xXxxx.....
        .......xxx......
        ................
        ................
        ................
        ................
    `),
    counter: grid(`
        ................
        ................
        ................
        ................
        ..oo......oo....
        ..oPo....oPo....
        ..oppo...oppo...
        ..oooo...oooo...
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        oWWWWWWWWWWWWWWo
        oWWWWWWWWWWWWWWo
        oWWWWWWWWWWWWWWo
        oooooooooooooooo
        ................
    `),
    sign: grid(`
        ................
        ................
        .oooooooooooooo.
        .oWwwwwwwwwwwWo.
        .oWwwWwwwWwwwWo.
        .oWwwwwwwwwwwWo.
        .oooooooooooooo.
        .......tt.......
        .......tt.......
        .......tt.......
        .......tt.......
        .......tt.......
        .......tt.......
        ......ottto.....
        ......ooooo.....
        ................
    `),
    bookshelf: grid(`
        oooooooooooooooo
        oWWWWWWWWWWWWWWo
        oWbkbrbkbybkbrWo
        oWbkbrbkbybkbrWo
        oWbkbrbkbybkbrWo
        oWWWWWWWWWWWWWWo
        oWrbkbybrbkbybWo
        oWrbkbybrbkbybWo
        oWrbkbybrbkbybWo
        oWWWWWWWWWWWWWWo
        oWkbybrbkbybrbWo
        oWkbybrbkbybrbWo
        oWkbybrbkbybrbWo
        oWWWWWWWWWWWWWWo
        oooooooooooooooo
        ................
    `),
    painting: grid(`
        ................
        ....oooooooo....
        ...oggggggggo...
        ...oggggggggo...
        ...oggGGGGggo...
        ...oggGllGggo...
        ...ogggGGgggo...
        ...oggggggggo...
        ...oggGGGGggo...
        ...oggggggggo...
        ....oooooooo....
        ................
        ................
        ................
        ................
        ................
    `),
    rugRed: grid(`
        hhhhhhhhhhhhhhhh
        hHHHHHHHHHHHHHHh
        hHhhhhhhhhhhhhHh
        hHhyyhhhhhhyyhHh
        hHhyyhhhhhhyyhHh
        hHhhhhhhhhhhhhHh
        hHhhhhhyyhhhhhHh
        hHhhhhhyyhhhhhHh
        hHhhhhhyyhhhhhHh
        hHhhhhhyyhhhhhHh
        hHhhhhhhhhhhhhHh
        hHhyyhhhhhhyyhHh
        hHhyyhhhhhhyyhHh
        hHhhhhhhhhhhhhHh
        hHHHHHHHHHHHHHHh
        hhhhhhhhhhhhhhhh
    `),
    rugBlue: grid(`
        bbbbbbbbbbbbbbbb
        bBBBBBBBBBBBBBBb
        bBbbbbbbbbbbbbBb
        bBbppbbbbbbppbBb
        bBbppbbbbbbppbBb
        bBbbbbbbbbbbbbBb
        bBbbbbbppbbbbbBb
        bBbbbbbppbbbbbBb
        bBbbbbbppbbbbbBb
        bBbbbbbppbbbbbBb
        bBbbbbbbbbbbbbBb
        bBbppbbbbbbppbBb
        bBbppbbbbbbppbBb
        bBbbbbbbbbbbbbBb
        bBBBBBBBBBBBBBBb
        bbbbbbbbbbbbbbbb
    `),
    plant: grid(`
        ................
        ......ooo.......
        ....oollloo.....
        ...olllLllllo...
        ...oLllllllLo...
        ..olllLlllLlllo.
        ..olLlllllllLlo.
        ...oLlllLlllLo..
        ....oollllloo...
        ......oooo......
        .....oWWWWo.....
        .....oWwwWo.....
        .....oWWWWo.....
        ......oWWo......
        ......oooo......
        ................
    `),
    crate: grid(`
        ................
        ................
        ................
        ..oooooooooooo..
        ..oWwwwwwwwwWo..
        ..oWWWWWWWWWWo..
        ..oWwwwwwwwwWo..
        ..oWwWwwwwWwWo..
        ..oWwwWwwWwwWo..
        ..oWwwwWWwwwWo..
        ..oWwwWwwWwwWo..
        ..oWwWwwwwWwWo..
        ..oWwwwwwwwwWo..
        ..oWWWWWWWWWWo..
        ..oooooooooooo..
        ................
    `),
    barrel: grid(`
        ................
        ................
        .....oooooo.....
        ....oWWWWWWo....
        ...oWwwwwwwWo...
        ...oMMMMMMMMo...
        ...oWwwwwwwWo...
        ...oWwwwwwwWo...
        ...oWwwwwwwWo...
        ...oMMMMMMMMo...
        ...oWwwwwwwWo...
        ...oWwwwwwwWo...
        ....oWWWWWWo....
        .....oooooo.....
        ................
        ................
    `),
    table: grid(`
        ................
        ................
        ......oo........
        .....oPpo.......
        .....oppo...oo..
        .....oooo..oPpo.
        ...........oppo.
        ...oooooooooooo.
        ..owwwwwwwwwwwwo
        ..oWWWWWWWWWWWWo
        ..oooooooooooooo
        ....oWo....oWo..
        ....oWo....oWo..
        ....oWo....oWo..
        ....ooo....ooo..
        ................
    `),
    fireplaceA: grid(`
        oooooooooooooooo
        oSssSssSssSssSso
        osssssssssssssso
        osooooooooooooso
        osokkkkkkkkkkoso
        osokkkyykkkkkoso
        osokkyYyykkykoso
        osokkyYYykyyyoso
        osokyyYYyyyYyoso
        osokyYYYYYyyyoso
        osoyyYYYYYYyyoso
        osoWWWWWWWWWWoso
        osssssssssssssso
        oSssSssSssSssSso
        oooooooooooooooo
        ................
    `),
    fireplaceB: grid(`
        oooooooooooooooo
        oSssSssSssSssSso
        osssssssssssssso
        osooooooooooooso
        osokkkkkkkkkkoso
        osokkkkkyykkkoso
        osokkykyYyykkoso
        osokyyykYYyykoso
        osokyYyyYYYyyoso
        osoyyYYYYYYyyoso
        osoyYYYYYYYYyoso
        osoWWWWWWWWWWoso
        osssssssssssssso
        oSssSssSssSssSso
        oooooooooooooooo
        ................
    `),
    fountainA: grid(`
        ................
        .......cc.......
        ......cCCc......
        .......cc.......
        ....ooooooo.....
        ...oSmmmmmmSo...
        ..oSccccccccSo..
        ..occCccccCcco..
        ..occcccccccco..
        ..oSccCccCccSo..
        ..oSSccccccSSo..
        ...oSSSSSSSSo...
        ....oooooooo....
        ................
        ................
        ................
    `),
    fountainB: grid(`
        ................
        ......c..c......
        .......cc.......
        ......cCCc......
        ....ooooooo.....
        ...oSmmmmmmSo...
        ..oSccccccccSo..
        ..occcCccCccco..
        ..ocCccccccCco..
        ..oSccccccccSo..
        ..oSSccCccCSSo..
        ...oSSSSSSSSo...
        ....oooooooo....
        ................
        ................
        ................
    `),
    flowerbed: grid(`
        ................
        ................
        ................
        ................
        ..oooooooooooo..
        .oWlflflflflfWo.
        .oWflflflflflWo.
        .oWlflflflflfWo.
        .oWWWWWWWWWWWWo.
        ..oooooooooooo..
        ................
        ................
        ................
        ................
        ................
        ................
    `),
    fence: grid(`
        ................
        ................
        ................
        ................
        ................
        ..t..........t..
        .ttt........ttt.
        ..t..........t..
        tttttttttttttttt
        ..t..........t..
        ..t..........t..
        tttttttttttttttt
        ..t..........t..
        ..t..........t..
        ................
        ................
    `),
    well: grid(`
        ......oooo......
        .....oWWWWo.....
        ....oWwwwwWo....
        ...oWWWWWWWWo...
        ...o.oWooWo.o...
        ...o.o....o.o...
        ...o.o....o.o...
        ..oooooooooooo..
        ..oSsSsSsSsSso..
        ..osSsSsSsSsSo..
        ..oSsSsSsSsSso..
        ..osSsSsSsSsSo..
        ..oooooooooooo..
        ................
        ................
        ................
    `),
    bench: grid(`
        ................
        ................
        ................
        ................
        ................
        .oooooooooooooo.
        .oWwwwwwwwwwwWo.
        .oWWWWWWWWWWWWo.
        .oooooooooooooo.
        ..oWo......oWo..
        ..oWo......oWo..
        ..ooo......ooo..
        ................
        ................
        ................
        ................
    `),
    brazier: grid(`
        ................
        ......yYy.......
        .....yYYYy......
        .....yYyYy......
        ......yyy.......
        .....oooooo.....
        ....oMMMMMMo....
        ....oMmmmmMo....
        .....oMMMMo.....
        ......oMMo......
        ......oMMo......
        ......oMMo......
        .....oMMMMo.....
        ....oMMMMMMo....
        ....oooooooo....
        ................
    `),
    carpet: grid(`
        hhhhhhhhhhhhhhhh
        hhhhhhhhhhhhhhhh
        hhyhhhhhhhhhhyhh
        hhhhhhhhhhhhhhhh
        hhhhhhhhhhhhhhhh
        hhhhhhhhhhhhhhhh
        hhhhhhhhhhhhhhhh
        hhhhhhhyyhhhhhhh
        hhhhhhhyyhhhhhhh
        hhhhhhhhhhhhhhhh
        hhhhhhhhhhhhhhhh
        hhhhhhhhhhhhhhhh
        hhhhhhhhhhhhhhhh
        hhyhhhhhhhhhhyhh
        hhhhhhhhhhhhhhhh
        hhhhhhhhhhhhhhhh
    `),
    longTable: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        oooooooooooooooo
        .oWo........oWo.
        .oWo........oWo.
        .oWo........oWo.
        .ooo........ooo.
        ................
        ................
    `),
    tree2: grid(`
        .......oo.......
        ......oLLo......
        .....olllLo.....
        ....olllllLo....
        ...ollLlllllo...
        ..olllllLlllLo..
        .ollLlllllllLLo.
        ..ooollllLoooo..
        ....olllllLo....
        ...olLllllllo...
        ..olllllLlllLo..
        .oLLLLLLLLLLLLo.
        ..ooooottoooo...
        .......tt.......
        ......oooo......
        ................
    `),
    dummy: grid(`
        ......oooo......
        .....oPppPo.....
        .....oPppPo.....
        ......oooo......
        ...oooWWWWooo...
        ..oWWWWWWWWWWo..
        ..oWWWWWWWWWWo..
        ...oooWWWWooo...
        .....oWWWWo.....
        .....oWWWWo.....
        ......oWWo......
        ......oWWo......
        ......oWWo......
        .....oWWWWo.....
        ....oWWWWWWo....
        ....oooooooo....
    `),
} satisfies Record<string, Grid>;

export type TileId = keyof typeof TILES;

/** Over a head: what the state is saying. Slots: o outline, p fill, y light. */
export const BUBBLES = {
    dots: grid(`
        .ooooooooo.
        opppppppppo
        oppopopoppo
        opppppppppo
        .ooooooooo.
        ...oo......
        ...o.......
    `),
    bang: grid(`
        .oooo.
        oyyyyo
        oyyyyo
        oyyyyo
        .oyyo.
        .oyyo.
        ..oo..
        .oyyo.
        ..oo..
    `),
    question: grid(`
        .ooooo.
        oyyyyyo
        oyooyyo
        .oo.oyo
        ...oyyo
        ...oyo.
        ...oo..
        ...oyo.
        ...oo..
    `),
    star: grid(`
        ....o....
        ...oyo...
        ...oyo...
        oooyyyooo
        oyyyyyyyo
        .oyyyyyo.
        ..oyyyo..
        .oyyoyyo.
        .oo...oo.
    `),
    zzz: grid(`
        ...........
        ......opppo
        .......oppo
        ......oppo.
        .....opppo.
        .oppo......
        ..opo......
        .opo.......
        opppo......
    `),
} satisfies Record<string, Grid>;

export const BUBBLE_COLOURS: Palette = palette({ o: '#1a1423', p: '#f2e8cf', y: '#f6d36b' });
