/**
 * Tempest, tile by tile: 16×16 ground, walls, furniture and ornaments, plus
 * the small things that float over heads.
 *
 * One palette for the whole town, so a lamp by the inn matches the lamp by
 * the hall. Slots:
 *   o outline   g/G grass   d/D path   w/W wood   s/S stone   r/R roof
 *   b/B banner  y/Y light   c/C crystal  k dark glass  p/P paper  m/M metal
 *   t trunk     l/L leaves  f flower   x/X smoke   h/H cushion
 */

import { grid, palette, type Grid, type Palette } from '../canvas';

export const TOWN: Palette = palette({
    o: '#1a1423',
    g: '#5f9c4b',
    G: '#4f8640',
    d: '#cfae7e',
    D: '#b59463',
    w: '#a8743f',
    W: '#82572b',
    s: '#8d929c',
    S: '#6c7280',
    r: '#4e6fae',
    R: '#3a5486',
    b: '#3b6ea8',
    B: '#2a4f7a',
    y: '#f6d36b',
    Y: '#fff4bf',
    c: '#7fd0f0',
    C: '#4aa7d8',
    k: '#2a2d3a',
    p: '#f2e8cf',
    P: '#d9ccab',
    m: '#c0c6d0',
    M: '#8a929f',
    t: '#6a4226',
    l: '#4f9a3c',
    L: '#3c7a2c',
    f: '#ee6f93',
    x: '#ececf2',
    X: '#bcc0cc',
    h: '#c8344a',
    H: '#9a2236',
});

/** A uniform tile with a few specks, made rather than typed. */
function speckled(base: string, speck: string, at: [number, number][]): Grid {
    const rows = Array.from({ length: 16 }, () => base.repeat(16).split(''));
    for (const [x, y] of at) rows[y][x] = speck;
    return grid(rows.map((r) => r.join('')).join('\n'));
}

export const TILES = {
    grass: speckled('g', 'G', [[5, 1], [12, 3], [2, 5], [9, 7], [3, 9], [14, 11], [6, 13], [11, 15]]),
    grassTuft: speckled('g', 'L', [[6, 4], [7, 4], [8, 4], [7, 3], [12, 10], [13, 10], [12, 9]]),
    path: speckled('d', 'D', [[3, 2], [11, 4], [7, 8], [14, 9], [1, 12], [9, 14]]),
    floor: grid(`
        wwwwwwwWwwwwwwww
        wwwwwwwWwwwwwwww
        wwwwwwwWwwwwwwww
        WWWWWWWWWWWWWWWW
        wwwWwwwwwwwwWwww
        wwwWwwwwwwwwWwww
        wwwWwwwwwwwwWwww
        WWWWWWWWWWWWWWWW
        wwwwwwwWwwwwwwww
        wwwwwwwWwwwwwwww
        wwwwwwwWwwwwwwww
        WWWWWWWWWWWWWWWW
        wwwWwwwwwwwwWwww
        wwwWwwwwwwwwWwww
        wwwWwwwwwwwwWwww
        WWWWWWWWWWWWWWWW
    `),
    stoneFloor: grid(`
        ssssssssSsssssss
        ssssssssSsssssss
        ssssssssSsssssss
        SSSSSSSSSSSSSSSS
        ssssSsssssssSsss
        ssssSsssssssSsss
        ssssSsssssssSsss
        SSSSSSSSSSSSSSSS
        ssssssssSsssssss
        ssssssssSsssssss
        ssssssssSsssssss
        SSSSSSSSSSSSSSSS
        ssssSsssssssSsss
        ssssSsssssssSsss
        ssssSsssssssSsss
        SSSSSSSSSSSSSSSS
    `),
    roof: grid(`
        oooooooooooooooo
        rrrrrrrrrrrrrrrr
        rRrrrrRrrrrRrrrr
        rrrrrrrrrrrrrrrr
        RRRRRRRRRRRRRRRR
        rrrrrrrrrrrrrrrr
        rrrRrrrrRrrrrRrr
        rrrrrrrrrrrrrrrr
        RRRRRRRRRRRRRRRR
        rrrrrrrrrrrrrrrr
        rRrrrrRrrrrRrrrr
        rrrrrrrrrrrrrrrr
        RRRRRRRRRRRRRRRR
        rrrrrrrrrrrrrrrr
        RRRRRRRRRRRRRRRR
        oooooooooooooooo
    `),
    roofDark: grid(`
        oooooooooooooooo
        RRRRRRRRRRRRRRRR
        RSRRRRSRRRRSRRRR
        RRRRRRRRRRRRRRRR
        SSSSSSSSSSSSSSSS
        RRRRRRRRRRRRRRRR
        RRRSRRRRSRRRRSRR
        RRRRRRRRRRRRRRRR
        SSSSSSSSSSSSSSSS
        RRRRRRRRRRRRRRRR
        RSRRRRSRRRRSRRRR
        RRRRRRRRRRRRRRRR
        SSSSSSSSSSSSSSSS
        RRRRRRRRRRRRRRRR
        SSSSSSSSSSSSSSSS
        oooooooooooooooo
    `),
    wall: grid(`
        ssssssssssssssss
        sSssssssSsssssss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        ssssSsssssssSsss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        ssssSsssssssSsss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        ssssssssssssssss
        oooooooooooooooo
    `),
    wallSide: grid(`
        ssssssssssssssss
        sSssssssSsssssss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        ssssSsssssssSsss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        ssssSsssssssSsss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
    `),
    windowDark: grid(`
        ssssssssssssssss
        sSssssssSsssssss
        sssoooooooooosss
        sssokkkkkkkkosss
        sssokkkkkkkkosss
        sssokkkkokkkosss
        sssoooooooooosss
        sssokkkkkkkkosss
        sssokkkkkkkkosss
        sssokkkkkkkkosss
        sssoooooooooosss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        ssssssssssssssss
        oooooooooooooooo
    `),
    windowLit: grid(`
        ssssssssssssssss
        sSssssssSsssssss
        sssoooooooooosss
        sssoyyyyyyyyosss
        sssoyYyyyyyyosss
        sssoyyyyoyyyosss
        sssoooooooooosss
        sssoyyyyyyyyosss
        sssoyyyyyyyyosss
        sssoyyyyyyyyosss
        sssoooooooooosss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        ssssssssssssssss
        oooooooooooooooo
    `),
    boarded: grid(`
        ssssssssssssssss
        sSssssssSsssssss
        sssoooooooooosss
        sssokkkkkkkkosss
        sssWWWkkkkkkosss
        sssokkWWWkkkosss
        sssokkkkkWWWosss
        sssokkkkkkkWWWss
        sssWWWkkkkkkosss
        sssokkWWWkkkosss
        sssoooooWWWoosss
        ssssssssssssssss
        SSSSSSSSSSSSSSSS
        sSssssssSsssssss
        ssssssssssssssss
        oooooooooooooooo
    `),
    door: grid(`
        ssssssssssssssss
        sSssssssSsssssss
        ssssoooooooossss
        sssoWWWWWWWWosss
        sssoWwWWWWwWosss
        sssoWWWWWWWWosss
        sssoWWWWWWWWosss
        sssoWWWWWWWWosss
        sssoWWWWWmWWosss
        sssoWWWWWWWWosss
        sssoWWWWWWWWosss
        sssoWWWWWWWWosss
        sssoWWWWWWWWosss
        sssoWWWWWWWWosss
        sssoWWWWWWWWosss
        oooooooooooooooo
    `),
    scaffold: grid(`
        t..............t
        tWWWWWWWWWWWWWWt
        t..............t
        t.....t........t
        t.....t........t
        tWWWWWWWWWWWWWWt
        t.....t........t
        t.....t...t....t
        t.....t...t....t
        tWWWWWWWWWWWWWWt
        t.........t....t
        t.........t....t
        t.........t....t
        tWWWWWWWWWWWWWWt
        t..............t
        t..............t
    `),
    deskOff: grid(`
        ................
        ................
        ....oooooooo....
        ...oCCCCCCCCo...
        ...oCkkkkkkCo...
        ...oCkkkkkkCo...
        ...oCCCCCCCCo...
        ....oooooooo....
        ......oMMo......
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        .oWo........oWo.
        .oWo........oWo.
        ................
        ................
    `),
    deskOn: grid(`
        ................
        ................
        ....oooooooo....
        ...oCCCCCCCCo...
        ...oCcYccccCo...
        ...oCccccccCo...
        ...oCCCCCCCCo...
        ....oooooooo....
        ......oMMo......
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        .oWo........oWo.
        .oWo........oWo.
        ................
        ................
    `),
    deskOn2: grid(`
        ................
        ................
        ....oooooooo....
        ...oCCCCCCCCo...
        ...oCccccccCo...
        ...oCcccYccCo...
        ...oCCCCCCCCo...
        ....oooooooo....
        ......oMMo......
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        .oWo........oWo.
        .oWo........oWo.
        ................
        ................
    `),
    nameplate: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..oooooooooooo..
        ..oppPpppPpppo..
        ..oppppppppppo..
        ..oooooooooooo..
        ......oWWo......
        ................
        ................
    `),
    lantern: grid(`
        ......oooo......
        .....oMMMMo.....
        ......oyyo......
        .....oyYYyo.....
        .....oyYYyo.....
        .....oyyyyo.....
        ......oyyo......
        ......oooo......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        ......oMMo......
        .....oMMMMo.....
        .....oooooo.....
    `),
    cushion: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....oooooooo....
        ..oohhhhhhhhoo..
        .ohhhhHhhhhhhho.
        .ohhhhhhhhhhhho.
        .oHHhhhhhhhhHHo.
        ..ooHHHHHHHHoo..
        ....oooooooo....
        ................
        ................
    `),
    scrolls1: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....ooooooooo...
        ...oppppppppPo..
        ...oPPPPPPPPPo..
        ...oooooooooo...
        ................
        ................
        ................
    `),
    scrolls2: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        .....ooooooooo..
        ....oppppppppPo.
        ....oPPPPPPPPPo.
        ....ooooooooooo.
        ...oppppppppPo..
        ...oPPPPPPPPPo..
        ...oooooooooo...
        ................
        ................
        ................
    `),
    scrolls3: grid(`
        ................
        ................
        ................
        ....ooooooooo...
        ...oppppppppPo..
        ...oPPPPPPPPPo..
        .....ooooooooo..
        ....oppppppppPo.
        ....oPPPPPPPPPo.
        ....ooooooooooo.
        ...oppppppppPo..
        ...oPPPPPPPPPo..
        ...oooooooooo...
        ................
        ................
        ................
    `),
    lamp: grid(`
        ......oooo......
        .....oyYYyo.....
        .....oyYYyo.....
        .....oyyyyo.....
        ......oooo......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        .......MM.......
        ......oMMo......
        .....oMMMMo.....
        ....oMMMMMMo....
        ....oooooooo....
    `),
    garden: grid(`
        ................
        ................
        ......f.........
        .....lfl....f...
        ......l....lfl..
        ..f.........l...
        .lfl......f.....
        ..l......lfl....
        ....f.....l.....
        ...lfl..........
        ....l....f......
        ........lfl.....
        .f.......l......
        lfl.......f.....
        .l.......lfl....
        ..........l.....
    `),
    banner: grid(`
        ......oooo......
        .....oMMMMo.....
        ......oMMo......
        ....oobbbboo....
        ....obbbbbbo....
        ....obBbbBbo....
        ....obbbbbbo....
        ....obbyybbo....
        ....obbyybbo....
        ....obbbbbbo....
        ....obBbbBbo....
        ....obbbbbbo....
        ....obb..bbo....
        ....oo....oo....
        .......MM.......
        ......oMMo......
    `),
    statue: grid(`
        ......oooo......
        .....ommmmo.....
        .....ommMmo.....
        ......ommo......
        ....oommmmoo....
        ...ommmmmmmmo...
        ...ommMmmMmmo...
        ...ommmmmmmmo...
        ....ommmmmmo....
        ....ommmmmmo....
        ....oMMMMMMo....
        ...oSSSSSSSSo...
        ..oSSSSSSSSSSo..
        ..oSsssssssSSo..
        ..oSSSSSSSSSSo..
        ..oooooooooooo..
    `),
    tree: grid(`
        ......oooo......
        ....oollllloo...
        ...ollllllllLo..
        ..olllllllllLLo.
        ..ollLlllllllLo.
        .ollllllllLllLLo
        .olLllllllllllLo
        .oLlllllLlllLLLo
        ..oLLlllllllLLo.
        ..ooLLLLLLLLLoo.
        ....oooottoooo..
        .......ott......
        .......ott......
        .......ott......
        ......oottoo....
        ......oooooo....
    `),
    chimney: grid(`
        ................
        ................
        ................
        ................
        ................
        ................
        .....oooooo.....
        .....oSSSSo.....
        .....osssso.....
        .....osSsso.....
        .....osssso.....
        .....oSsSso.....
        .....osssso.....
        .....oooooo.....
        ................
        ................
    `),
    smokeA: grid(`
        ................
        ................
        ......xx........
        .....xXxx.......
        ......xx........
        ................
        ........xx......
        .......xxXx.....
        ........xx......
        ................
        ......xxx.......
        .....xXxxx......
        ......xxx.......
        ................
        ................
        ................
    `),
    smokeB: grid(`
        ................
        ........xx......
        .......xXxx.....
        ........xx......
        ................
        .....xx.........
        ....xxXx........
        .....xx.........
        ................
        .......xxx......
        ......xXxxx.....
        .......xxx......
        ................
        ................
        ................
        ................
    `),
    counter: grid(`
        ................
        ................
        ................
        ................
        ..oo......oo....
        ..oPo....oPo....
        ..oppo...oppo...
        ..oooo...oooo...
        oooooooooooooooo
        owwwwwwwwwwwwwwo
        oWWWWWWWWWWWWWWo
        oWWWWWWWWWWWWWWo
        oWWWWWWWWWWWWWWo
        oWWWWWWWWWWWWWWo
        oooooooooooooooo
        ................
    `),
    sign: grid(`
        ................
        ................
        .oooooooooooooo.
        .oWwwwwwwwwwwWo.
        .oWwwWwwwWwwwWo.
        .oWwwwwwwwwwwWo.
        .oooooooooooooo.
        .......tt.......
        .......tt.......
        .......tt.......
        .......tt.......
        .......tt.......
        .......tt.......
        ......ottto.....
        ......ooooo.....
        ................
    `),
} satisfies Record<string, Grid>;

export type TileId = keyof typeof TILES;

/** Over a head: what the state is saying. Slots: o outline, p fill, y light. */
export const BUBBLES = {
    dots: grid(`
        .ooooooooo.
        opppppppppo
        oppopopoppo
        opppppppppo
        .ooooooooo.
        ...oo......
        ...o.......
    `),
    bang: grid(`
        .oooo.
        oyyyyo
        oyyyyo
        oyyyyo
        .oyyo.
        .oyyo.
        ..oo..
        .oyyo.
        ..oo..
    `),
    question: grid(`
        .ooooo.
        oyyyyyo
        oyooyyo
        .oo.oyo
        ...oyyo
        ...oyo.
        ...oo..
        ...oyo.
        ...oo..
    `),
    star: grid(`
        ....o....
        ...oyo...
        ...oyo...
        oooyyyooo
        oyyyyyyyo
        .oyyyyyo.
        ..oyyyo..
        .oyyoyyo.
        .oo...oo.
    `),
    zzz: grid(`
        ...........
        ......opppo
        .......oppo
        ......oppo.
        .....opppo.
        .oppo......
        ..opo......
        .opo.......
        opppo......
    `),
} satisfies Record<string, Grid>;

export const BUBBLE_COLOURS: Palette = palette({ o: '#1a1423', p: '#f2e8cf', y: '#f6d36b' });
